modLoader="javafml"
loaderVersion="[4,)"
license="AGPL-3.0-or-later"
[[mods]]
modId="serfdom"
version="${version}"
displayName="Serfdom"
authors="Rusty Shackleford and nfx"
description='''Villagers you hire or take in chains live and work at your base. Give a worker a bed and a Work Post, and it cuts down the trees, harvests the crops, cooks or smiths around the post and sorts what it makes into your chests. A captive works longer and slower, hums a work song, and now and then slips away home at night.'''
[[mixins]]
config="serfdom.mixins.json"
[[dependencies.serfdom]]
modId="neoforge"
type="required"
versionRange="[21.1.248,)"
ordering="NONE"
side="BOTH"
[[dependencies.serfdom]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[dependencies.serfdom]]
modId="villagedeed"
type="optional"
versionRange="[2.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.serfdom]]
modId="farmersdelight"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"
[[dependencies.serfdom]]
modId="thief"
type="optional"
versionRange="[1.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.serfdom]]
modId="villagelaw"
type="optional"
versionRange="[1.1,)"
ordering="AFTER"
side="BOTH"
[[dependencies.serfdom]]
modId="vanillawheels"
type="optional"
versionRange="[1.11,)"
ordering="AFTER"
side="BOTH"
